# Site settings
title: Agendae
email: kevinzweerink@gmail.com
description: A new format for developing news stories
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://kevinzweerink.com" # the base hostname & protocol for your site
twitter_username: kevinzweerink
github_username:  kevinzweerink

# Build settings
markdown: kramdown
